import type { Invitation, Member, Role } from "@/components/dashboard/team/team-types";

export const members: Member[] = [
	{
		id: "connor",
		name: "Connor Love",
		email: "connor@briefly.so",
		initials: "CL",
		role: "Owner",
		type: "internal",
		access: "Full workspace access",
		projects: "12 active projects",
		activity: "Last active 2m ago",
		status: "Online",
		lastActive: "2m ago",
		assignedProjects: ["Acme Website Redesign", "Nova Launch", "Brightside Landing Page"],
		recentActivity: [
			{ label: "Shared weekly client recap", time: "18m ago" },
			{ label: "Approved homepage review", time: "Today" },
		],
	},
	{
		id: "maya",
		name: "Maya Chen",
		email: "maya@briefly.so",
		initials: "MC",
		role: "Designer",
		type: "internal",
		access: "Projects, Files, Portals",
		projects: "4 assigned projects",
		activity: "Updated homepage review 1h ago",
		status: "Active",
		lastActive: "1h ago",
		assignedProjects: ["Acme Website Redesign", "Nova Launch", "Studio Rebrand"],
		recentActivity: [
			{ label: "Updated homepage review", time: "2h ago" },
			{ label: "Uploaded BrandAssets.zip", time: "Yesterday" },
		],
	},
	{
		id: "jordan",
		name: "Jordan Ellis",
		email: "jordan@briefly.so",
		initials: "JE",
		role: "Admin",
		type: "internal",
		access: "Workspace + project management",
		projects: "8 assigned projects",
		activity: "Sent Nova launch update yesterday",
		status: "Away",
		lastActive: "Yesterday",
		assignedProjects: ["Nova Launch", "Forge Fitness", "Acme Website Redesign"],
		recentActivity: [
			{ label: "Sent Nova launch update", time: "Yesterday" },
			{ label: "Resolved client request", time: "May 7" },
		],
	},
	{
		id: "dana",
		name: "Dana Ellis",
		email: "dana@acme.com",
		initials: "DE",
		role: "Client",
		type: "client",
		access: "Portal-only access",
		projects: "3 active portals",
		activity: "Viewed homepage review today",
		status: "Viewing portal",
		lastActive: "Today",
		assignedProjects: ["Acme Website Redesign", "Acme Support Portal"],
		recentActivity: [
			{ label: "Viewed homepage review", time: "Today" },
			{ label: "Commented on mobile header", time: "Yesterday" },
		],
	},
	{
		id: "sam",
		name: "Sam Rivera",
		email: "sam@briefly.so",
		initials: "SR",
		role: "Designer",
		type: "internal",
		access: "Projects, Files, Updates",
		projects: "2 assigned projects",
		activity: "Uploaded logo exports 3h ago",
		status: "Active",
		lastActive: "3h ago",
		assignedProjects: ["Brightside Landing Page", "Studio Rebrand"],
		recentActivity: [
			{ label: "Uploaded logo exports", time: "3h ago" },
			{ label: "Marked wireframes ready", time: "Yesterday" },
		],
	},
	{
		id: "lena",
		name: "Lena Ortiz",
		email: "lena@nova.co",
		initials: "LO",
		role: "Client",
		type: "client",
		access: "Portal-only visibility",
		projects: "1 active portal",
		activity: "Approved launch copy yesterday",
		status: "Viewing portal",
		lastActive: "Yesterday",
		assignedProjects: ["Nova Launch"],
		recentActivity: [
			{ label: "Approved launch copy", time: "Yesterday" },
			{ label: "Opened weekly update", time: "May 6" },
		],
	},
];

export const roles: Role[] = [
	{
		name: "Owner",
		description: "Full workspace control",
		permissions: [
			{ group: "Projects", items: [{ label: "View", enabled: true }, { label: "Edit", enabled: true }] },
			{ group: "Files", items: [{ label: "Upload", enabled: true }, { label: "Download", enabled: true }] },
			{ group: "Workspace", items: [{ label: "Billing", enabled: true }, { label: "Team settings", enabled: true }] },
		],
	},
	{
		name: "Admin",
		description: "Workspace + project management",
		permissions: [
			{ group: "Projects", items: [{ label: "View", enabled: true }, { label: "Edit", enabled: true }] },
			{ group: "Files", items: [{ label: "Upload", enabled: true }, { label: "Download", enabled: true }] },
			{ group: "Workspace", items: [{ label: "Billing", enabled: false }, { label: "Team settings", enabled: true }] },
		],
	},
	{
		name: "Designer",
		description: "Projects, files, approvals",
		permissions: [
			{ group: "Projects", items: [{ label: "View", enabled: true }, { label: "Edit", enabled: true }] },
			{ group: "Files", items: [{ label: "Upload", enabled: true }, { label: "Download", enabled: true }] },
			{ group: "Portals", items: [{ label: "View", enabled: true }, { label: "Respond", enabled: true }] },
			{ group: "Workspace", items: [{ label: "Billing", enabled: false }, { label: "Team settings", enabled: false }] },
		],
	},
	{
		name: "Client",
		description: "Portal-only visibility",
		permissions: [
			{ group: "Projects", items: [{ label: "View", enabled: false }, { label: "Edit", enabled: false }] },
			{ group: "Files", items: [{ label: "Upload", enabled: true }, { label: "Download", enabled: true }] },
			{ group: "Portals", items: [{ label: "View", enabled: true }, { label: "Respond", enabled: true }] },
			{ group: "Workspace", items: [{ label: "Billing", enabled: false }, { label: "Team settings", enabled: false }] },
		],
	},
];

export const invitations: Invitation[] = [
	{ email: "alex@agency.com", sent: "Invited yesterday", state: "Not opened" },
	{ email: "sarah@client.com", sent: "Opened 2h ago", state: "Expires in 5 days" },
];
